# This workflow will install Python dependencies and run ruff to lint the project 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ruff

    - name: Lint with Ruff on a basic set of rules
      run: |
        ruff check libdebug --output-format=github --config ruff-errors.toml

    - name: Lint with Ruff on an extended ruleset but always return success
      run: |
        ruff check libdebug --output-format=github --exit-zero
